CREATE TABLE resume_templates (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  template_key VARCHAR(50) NOT NULL,
  title VARCHAR(100),
  thumbnail VARCHAR(255),
  status TINYINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE admins(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(120) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);